In [5]:
from time import sleep

x = input('Pesquise no FILL ou digite um URL: ')
print(f'Verificamos que vc quis pesquisar sobre {x}, espere um momento...')

sleep(3)

opcao = 0
while opcao != 5:
    print('''
        [1] painel de indicador
        [2] gráfico em maps
        [3] resumidamente
        [5] sair do programa
    ''')
    opcao = int(input('Qual é a sua opção? '))
    
    if opcao == 5:
        print('Finalizando...')
        print('É isso, terminamos. Mais uma vez, muito obrigado por usar FILL')
        exit()
        
    elif opcao == 1:
        def opc():
            print('''
                [a] prosseguir
                [c] voltar para menu
                ''')
        opc()
        escolha = input("Selecione uma opção: ")
        if escolha == "a": 
            from pyecharts import options as opts
            from pyecharts.charts import Bar,Timeline
            tl = Timeline()
            bar = Bar()
            bar.add_xaxis(["Nordeste", "Norte", "Centro-Oeste", "Sudeste e Sul"])
            bar.add_yaxis("Jovens %", [13.9, 7.6, 4.9, 3.3])
            bar.add_yaxis("Idosos %", [37.2, 25.5, 16.6, 9.7])
            bar.set_global_opts(title_opts=opts.TitleOpts(title="índice de analfabetos"))
            bar.render_notebook()
        elif escolha == 'c':
            print('Voltando..')
        else:
            print('Opção inválida, tente novamente')
            
    elif opcao == 2:
        def opc():
            print('''
                [a] presseguir
                [c] voltar para menu
                ''')
        opc()
        escolha = input("Selecione uma opção: ")
        if escolha == "a": 
            from pyecharts.charts import Map
            from pyecharts import options as opts
            import pandas as pd

            tabela_educacao = pd.read_csv('tabela_wikipedia_educacao_eng.csv', sep = ",")


            map = Map()
            map.add('',tabela_educacao[['Country','Literate_rate']].values.tolist(),maptype='world')
            map.set_series_opts(label_opts=opts.LabelOpts(is_show=False)) 
            map.set_global_opts(
                visualmap_opts=opts.VisualMapOpts(min_=0,max_=100),
                legend_opts=opts.LegendOpts(is_show=False)
            )
            map.render_notebook() 
            #map.render('mapa_mundi_educacao_eng')
        elif escolha == 'c':
            print('Voltando..')
        else:
            print('Opção inválida, tente novamente')
            
    elif opcao == 3:
        def opc():
            print('''
                [a] prosseguir
                [c] voltar para menu
                ''')
        opc()
        escolha = input("Selecione uma opção: ")
        if escolha == "a":
            from newspaper import Article
            url1 = 'https://g1.globo.com/jornal-nacional/noticia/2021/08/03/estados-e-municipios-reduziram-investimentos-em-educacao-em-r-21-bi-em-2020.ghtml'
            article = Article(url1)
            article.download()
            article.parse()
            article.nlp()
            a = article.summary
            x = a.strip()
            print(x)
            url2 = 'https://educa.ibge.gov.br/jovens/conheca-o-brasil/populacao/18317-educacao.html'
            article = Article(url2)
            article.download()
            article.parse()
            article.nlp()
            b = article.summary
            y = a.strip()
            print(y)
            url3 = 'https://blog.wyden.com.br/noticias/pesquisa-do-ibge-aponta-que-brasil-ainda-tem-11-milhoes-de-analfabetos/#:~:text=Com%20rela%C3%A7%C3%A3o%20%C3%A0s%20regi%C3%B5es%20do,taxas%2C%203%2C3%25'
            article = Article(url3)
            article.download()
            article.parse()
            article.nlp()
            c = article.summary
            w = c.strip()
            print(w)
            url4 = 'http://www.saocarlos.usp.br/estudo-da-usp-mostra-que-dados-do-enem-podem-contribuir-para-a-construcao-de-futuras-politicas-educacionais/'
            article = Article(url4)
            article.download()
            article.parse()
            article.nlp()
            d = article.summary
            z = d.strip()
            print(z)
            url5 = 'https://www12.senado.leg.br/noticias/infomaterias/2021/07/pandemia-acentua-deficit-educacional-e-exige-acoes-do-poder-publico#:~:text=Diante%20da%20pandemia%2C%20o%20Minist%C3%A9rio,uma%2C%20duas%2C%20tr%C3%AAs%20vezes.'
            article = Article(url5)
            article.download()
            article.parse()
            article.nlp()
            e = article.text
            r = e.strip()
            print(r)
        elif escolha == 'c':
            print('Voltando..')
        else:
            print('Opção inválida, tente novamente')
    else:
        print('Opção inválida, tente novamente')

Pesquise no FILL ou digite um URL: educacao
Verificamos que vc quis pesquisar sobre educacao, espere um momento...

        [1] painel de indicador
        [2] gráfico em maps
        [3] resumidamente
        [5] sair do programa

Qual é a sua opção? 1

                [a] prosseguir
                [c] voltar para menu

Selecione uma opção: a

        [1] painel de indicador
        [2] gráfico em maps
        [3] resumidamente
        [5] sair do programa

Qual é a sua opção? 3

                [a] prosseguir
                [c] voltar para menu

Selecione uma opção: a
Educação perde R$ 21 bilhões em investimentos na educação, no primeiro ano da pandemiaEm 2020, o primeiro ano da pandemia que afastou das escolas professores e alunos, os estados e os municípios brasileiros investiram em educação R$ 21 bilhões a menos do que no ano anterior.
E, mesmo diante de uma tarefa enorme, o poder público reduziu os investimentos em educação em 2020 na comparação com 2019.
É o que mostra o Anuário da Educação - um raio-X do ensino no país.
Capítulos anteriores terão que ser revistos, ao mesmo tempo em que se avança na história: um planejamento que leva tempo e custa dinheiro.
O Conselho Nacional de Secretários Estaduais de Educação afirmou que redução nos investimentos pode ser explicada em alguns casos pela retirada do pagamento dos aposentados da conta da educação.
Educação perde R$ 21 bilhões em investimentos na educação, no primeiro ano da pandemiaEm 2020, o primeiro ano da pandemia que afastou das escolas professores e alunos, os estados e os municípios brasileiros investiram em educação R$ 21 bilhões a menos do que no ano anterior.
E, mesmo diante de uma tarefa enorme, o poder público reduziu os investimentos em educação em 2020 na comparação com 2019.
É o que mostra o Anuário da Educação - um raio-X do ensino no país.
Capítulos anteriores terão que ser revistos, ao mesmo tempo em que se avança na história: um planejamento que leva tempo e custa dinheiro.
O Conselho Nacional de Secretários Estaduais de Educação afirmou que redução nos investimentos pode ser explicada em alguns casos pela retirada do pagamento dos aposentados da conta da educação.
Mesmo com a diminuição, que representa aproximadamente 200 mil indivíduos, o país ainda conta com 11 milhões de pessoas que não sabem ler e escrever.
De acordo com o IBGE, analfabetos são cidadãos que têm 15 anos de idade ou mais e eles não conseguem formular nem pequenos textos.
Entre aqueles com 60 anos ou mais, a pesquisa registra queda e o índice atual de analfabetos é de 18%.
Esta lei, estabelecia que, em 2015, o Brasil deveria alcançar a meta de 6,5% de analfabetos com 15 anos ou mais, sendo que, em 2024, a taxa deverá zerar.
Já entre os que têm 60 anos ou mais, as taxas são de 37,2%, no Nordeste; 25,5%, no Norte; 16,6%, no Centro-Oeste; 9,7%, no Sudeste; e 9,5%, na região Sul do Brasil.
Depois disso, os alunos foram divididos em três grupos: o dos que tiveram “baixo desempenho”, “médio desempenho” e “alto desempenho”.
Entre 2012 e 2017, os grupos de baixo e médio desempenho foram majoritariamente formados por alunos de escolas públicas.
Um exemplo é o da região Norte, que apresentou durante todos os anos maior taxa de participação de alunos da rede pública.
“De maneira geral, os alunos com deficiência têm saído das escolas públicas e ido para as escolas privadas.
Já em 2018, a informação do tipo de escola dos alunos foi omitida pela maioria dos estudantes.
Enem

Entre os estudantes que ingressaram no 3º ano do ensino médio em 2021, está Marília Silva, 17 anos, que sonha cursar a faculdade de direito. Aluna de uma escola pública em tempo integral, em Aparecida de Goiânia (GO), ela segue uma extensa rotina de estudos: são mais de 10 horas por dia. Assim que terminam as aulas, que vão de 7h às 17h, a jovem se desdobra em um cursinho preparatório para vestibulares.

A maratona servirá como base para diversas provas de ingresso ao ensino superior, mas Marília concentra os esforços para o Exame Nacional do Ensino Médio (Enem). No entanto, segundo o levantamento Juventudes e a Pandemia do Coronavírus, do Conselho Nacional da Juventude (Conjuve), Marília se encaixa em um pequeno percentual de jovens que ainda têm pretensão em fazer o exame — o número que vem caindo do ano passado para cá.

Na edição de 2020, 52% dos entrevistados disseram não ter a pretensão de realizar a prova. Ao final, 73% não se inscreveram. Neste ano, o número de desinteressados apresenta-se menor (45%), mas o que chama a atenção é o crescimento da indecisão: 29% ainda não sabem se vão fazer o exame. Para o presidente da Conjuve, o percentual não se trata de desinteresse, mas sim de desilusão.

— Mais do que o ingresso no ensino superior, o Enem também representa o sonho de um futuro melhor para milhões jovens em todo o país. Existe um sentimento de frustração, cansaço e falta de perspectivas, além de uma sensação de ausência do Estado frente aos desafios enfrentados pela população jovem. Tudo isso gera um ambiente de insegurança que acaba por refletir na desistência do exame — afirma.

A dificuldade em se preparar também pode ser um dos motivos para a dúvida. Entre 2020 e 2021, caiu de 33% para 25% o número de jovens que estão conseguindo estudar e aumentou de 56% para 74% aqueles preocupados com o desempenho.

Na quinta-feira (15), informe distribuído pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), responsável pela realização do Enem, mostrou que o desânimo detectado pela pesquisa teve consequências: as versões impressa e digital do exame tiveram 4.004.764 pessoas inscritas, número que ainda precisa ser confirmado pelo processamento do pagamento das taxas de inscrição. A Guia de Recolhimento da União (GRU Cobrança), no valor de R$ 85, poderá ser paga pelos não isentos até segunda-feira, 19 de julho.

Até o encerramento das inscrições, às 23h59 da quarta-feira (14), haviam sido registradas 3.903.664 inscrições para a versão impressa e 101.100 para a digital. O total é o menor desde 2009 (4.148.721), quando foi aplicado pela primeira vez o atual formato de provas, e 32% menor do que as inscrições em 2020 (5.893.369). A desistência no ano passado, no entanto, foi expressiva: 3 milhões (mais que a metade dos inscritos) não compareceram a nenhum dos dois dias, e 2,8 milhões compareceram aos dois ou a pelo menos um dia de prova. Em 2021, o Enem será realizado nos dias 21 e 28 de novembro, tanto na modalidade impressa quanto na digital.

        [1] painel de indicador
        [2] gráfico em maps
        [3] resumidamente
        [5] sair do programa

Qual é a sua opção? 5
Finalizando...
É isso, terminamos. Mais uma vez, muito obrigado por usar FILL

***RESUMIDAMENTE***

In [9]:
from newspaper import Article
url1 = 'https://g1.globo.com/jornal-nacional/noticia/2021/08/03/estados-e-municipios-reduziram-investimentos-em-educacao-em-r-21-bi-em-2020.ghtml'
article = Article(url1)
article.download()
article.parse()
article.nlp()
a = article.summary
x = a.strip()
print(x)

Educação perde R$ 21 bilhões em investimentos na educação, no primeiro ano da pandemiaEm 2020, o primeiro ano da pandemia que afastou das escolas professores e alunos, os estados e os municípios brasileiros investiram em educação R$ 21 bilhões a menos do que no ano anterior.
E, mesmo diante de uma tarefa enorme, o poder público reduziu os investimentos em educação em 2020 na comparação com 2019.
É o que mostra o Anuário da Educação - um raio-X do ensino no país.
Capítulos anteriores terão que ser revistos, ao mesmo tempo em que se avança na história: um planejamento que leva tempo e custa dinheiro.
O Conselho Nacional de Secretários Estaduais de Educação afirmou que redução nos investimentos pode ser explicada em alguns casos pela retirada do pagamento dos aposentados da conta da educação.

In [4]:
from newspaper import Article
url2 = 'https://educa.ibge.gov.br/jovens/conheca-o-brasil/populacao/18317-educacao.html'
article = Article(url2)
article.download()
article.parse()
article.nlp()
b = article.summary
y = a.strip()
print(y)

Em 2017, o percentual de brasileiros de 25 anos ou mais sem a educação básica era de 53,9%.
Pessoas de 25 anos ou mais de idade por nível de instrução no Brasil (%) Mais da metade desta população (52,6%) têm até o ensino médio incompleto.
Outros 32,9% disseram que não voltam a estudar porque estão trabalhando ou procurando emprego, e 15,9% apontaram que não estudam porque precisam se dedicar aos afazeres domésticos.
, índice superior ao registrado em 2017, quando era de 32,7%.
Entre a população de 25 anos ou mais, a taxa de escolarização era de 4,6% em 2018.

In [12]:
from newspaper import Article
url3 = 'https://blog.wyden.com.br/noticias/pesquisa-do-ibge-aponta-que-brasil-ainda-tem-11-milhoes-de-analfabetos/#:~:text=Com%20rela%C3%A7%C3%A3o%20%C3%A0s%20regi%C3%B5es%20do,taxas%2C%203%2C3%25'
article = Article(url3)
article.download()
article.parse()
article.nlp()
c = article.summary
w = c.strip()
print(w)

Mesmo com a diminuição, que representa aproximadamente 200 mil indivíduos, o país ainda conta com 11 milhões de pessoas que não sabem ler e escrever.
De acordo com o IBGE, analfabetos são cidadãos que têm 15 anos de idade ou mais e eles não conseguem formular nem pequenos textos.
Entre aqueles com 60 anos ou mais, a pesquisa registra queda e o índice atual de analfabetos é de 18%.
Esta lei, estabelecia que, em 2015, o Brasil deveria alcançar a meta de 6,5% de analfabetos com 15 anos ou mais, sendo que, em 2024, a taxa deverá zerar.
Já entre os que têm 60 anos ou mais, as taxas são de 37,2%, no Nordeste; 25,5%, no Norte; 16,6%, no Centro-Oeste; 9,7%, no Sudeste; e 9,5%, na região Sul do Brasil.

In [4]:
from newspaper import Article
url4 = 'http://www.saocarlos.usp.br/estudo-da-usp-mostra-que-dados-do-enem-podem-contribuir-para-a-construcao-de-futuras-politicas-educacionais/'
article = Article(url4)
article.download()
article.parse()
article.nlp()
d = article.summary
z = d.strip()
print(z)

Depois disso, os alunos foram divididos em três grupos: o dos que tiveram “baixo desempenho”, “médio desempenho” e “alto desempenho”.
Entre 2012 e 2017, os grupos de baixo e médio desempenho foram majoritariamente formados por alunos de escolas públicas.
Um exemplo é o da região Norte, que apresentou durante todos os anos maior taxa de participação de alunos da rede pública.
“De maneira geral, os alunos com deficiência têm saído das escolas públicas e ido para as escolas privadas.
Já em 2018, a informação do tipo de escola dos alunos foi omitida pela maioria dos estudantes.

In [3]:
from newspaper import Article
url5 = 'https://www12.senado.leg.br/noticias/infomaterias/2021/07/pandemia-acentua-deficit-educacional-e-exige-acoes-do-poder-publico#:~:text=Diante%20da%20pandemia%2C%20o%20Minist%C3%A9rio,uma%2C%20duas%2C%20tr%C3%AAs%20vezes.'
article = Article(url5)
article.download()
article.parse()
article.nlp()
e = article.text
r = e.strip()
print(r)

Enem

Entre os estudantes que ingressaram no 3º ano do ensino médio em 2021, está Marília Silva, 17 anos, que sonha cursar a faculdade de direito. Aluna de uma escola pública em tempo integral, em Aparecida de Goiânia (GO), ela segue uma extensa rotina de estudos: são mais de 10 horas por dia. Assim que terminam as aulas, que vão de 7h às 17h, a jovem se desdobra em um cursinho preparatório para vestibulares.

A maratona servirá como base para diversas provas de ingresso ao ensino superior, mas Marília concentra os esforços para o Exame Nacional do Ensino Médio (Enem). No entanto, segundo o levantamento Juventudes e a Pandemia do Coronavírus, do Conselho Nacional da Juventude (Conjuve), Marília se encaixa em um pequeno percentual de jovens que ainda têm pretensão em fazer o exame — o número que vem caindo do ano passado para cá.

Na edição de 2020, 52% dos entrevistados disseram não ter a pretensão de realizar a prova. Ao final, 73% não se inscreveram. Neste ano, o número de desinteressados apresenta-se menor (45%), mas o que chama a atenção é o crescimento da indecisão: 29% ainda não sabem se vão fazer o exame. Para o presidente da Conjuve, o percentual não se trata de desinteresse, mas sim de desilusão.

— Mais do que o ingresso no ensino superior, o Enem também representa o sonho de um futuro melhor para milhões jovens em todo o país. Existe um sentimento de frustração, cansaço e falta de perspectivas, além de uma sensação de ausência do Estado frente aos desafios enfrentados pela população jovem. Tudo isso gera um ambiente de insegurança que acaba por refletir na desistência do exame — afirma.

A dificuldade em se preparar também pode ser um dos motivos para a dúvida. Entre 2020 e 2021, caiu de 33% para 25% o número de jovens que estão conseguindo estudar e aumentou de 56% para 74% aqueles preocupados com o desempenho.

Na quinta-feira (15), informe distribuído pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (Inep), responsável pela realização do Enem, mostrou que o desânimo detectado pela pesquisa teve consequências: as versões impressa e digital do exame tiveram 4.004.764 pessoas inscritas, número que ainda precisa ser confirmado pelo processamento do pagamento das taxas de inscrição. A Guia de Recolhimento da União (GRU Cobrança), no valor de R$ 85, poderá ser paga pelos não isentos até segunda-feira, 19 de julho.

Até o encerramento das inscrições, às 23h59 da quarta-feira (14), haviam sido registradas 3.903.664 inscrições para a versão impressa e 101.100 para a digital. O total é o menor desde 2009 (4.148.721), quando foi aplicado pela primeira vez o atual formato de provas, e 32% menor do que as inscrições em 2020 (5.893.369). A desistência no ano passado, no entanto, foi expressiva: 3 milhões (mais que a metade dos inscritos) não compareceram a nenhum dos dois dias, e 2,8 milhões compareceram aos dois ou a pelo menos um dia de prova. Em 2021, o Enem será realizado nos dias 21 e 28 de novembro, tanto na modalidade impressa quanto na digital.

In [9]:
from newspaper import Article
url6 = 'https://www.futura.org.br/educacao-brasileira-na-pandemia-em-2020-e-os-desafios-de-2021/'
article = Article(url6)
article.download()
article.parse()
article.nlp()
f = article.summary
t = f.strip()
print(t)

Nesse sentido, faz-se necessária a consulta de diversas fontes de dados que se complementem entre si, permitindo uma leitura mais rica do que foi a educação brasileira na pandemia em 2020.
Só assim é possível que se trace estratégias efetivas e factíveis para uma educação básica para todas e todos, em 2021.
Diante de tamanha urgência, fazer com que os estudantes seguissem com os estudos, em contato com os materiais e as tarefas escolares, por meio físico ou pela internet, foi tema constante das conversas sobre educação no país.
Conectividade – o maior desafioA dificuldade de acesso aos conteúdos escolares se revelou o maior obstáculo para os estudantes.
Fazer com que estudantes tenham meios de se conectar às atividades escolares de forma remota é, portanto, tema urgente.

In [1]:
from newspaper import Article
url7 = 'https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/30774-ibge-divulga-o-rendimento-domiciliar-per-capita-e-o-coeficiente-de-desequilibrio-regional-para-2020#:~:text=Em%202020%2C%20o%20rendimento%20nominal,e%20CDR%20de%200%2C67.'
article = Article(url7)
article.download()
article.parse()
article.nlp()
g = article.summary
u = g.strip()
print(u)

O IBGE divulga hoje os valores de rendimento nominal mensal domiciliar per capita (RDPC) e os Coeficientes de Desequilíbrio Regional (CDR) referentes a 2020 para o Brasil e três Grandes Regiões: Norte, Nordeste e Centro-Oeste, calculados com base na Pesquisa Nacional por Amostra de Domicílios (PNAD) Contínua.
O Nordeste teve rendimento de R$ 916 e um CDR de 0,66.
Já o Norte teve rendimento de R$ 925 e CDR de 0,67.
Os coeficientes são calculados com base nos valores de rendimentos regionais em comparação com a média nacional.
Para o cálculo do CDR, são considerados os rendimentos de trabalho e de outras fontes.

***GRAFICO***

In [2]:
from pyecharts import options as opts
from pyecharts.charts import Bar,Timeline
tl = Timeline()
bar = Bar()
bar.add_xaxis(["Nordeste", "Norte", "Centro-Oeste", "Sudeste e Sul"])
bar.add_yaxis("Jovens % (acima de 15 anos)", [13.9, 7.6, 4.9, 3.3])
bar.add_yaxis("Idosos % (acima de 60 anos)", [37.2, 25.5, 16.6, 9.7])
bar.set_global_opts(title_opts=opts.TitleOpts(title="índice de analfabetismo"))
#bar.render("índice de analfabetismo.html")
bar.render_notebook()

In [5]:
from pyecharts.charts import Bar,Line

bar=Bar()
bar.add_xaxis(["Nordeste","Norte","Centro-Oeste","Sudeste e Sul"])
bar.add_yaxis("Jovens % (acima de 15 anos)",[13.9, 7.6, 4.9, 3.3])
bar.add_yaxis("Idosos % (acima de 60 anos)",[37.2, 25.5, 16.6, 9.7])
line=Line()
line.add_xaxis(["Nordeste","Norte","Centro-Oeste","Sudeste e Sul"])
line.add_yaxis("RENDA",[0])
line.add_yaxis("RENDA",[0])
line.overlap(bar)
line.render_notebook()

In [6]:
from pyecharts import options as opts
from pyecharts.charts import Bar,Timeline
t2 = Timeline()
bar = Bar()
bar.add_xaxis(["2012","2013","2014","2015","2016","2017"])
bar.add_yaxis("Nordeste", [679, 682, 693, 720,726,728])
bar.add_yaxis("Norte", [676, 685, 690,702,714,719])
bar.add_yaxis("Centro-Oeste", [683, 694, 694, 717, 725.5,728])
bar.add_yaxis("Sudeste", [699, 694, 693, 715, 725.5, 724])
bar.add_yaxis("Sul", [678,680,675,691,703,706])
bar.set_global_opts(title_opts=opts.TitleOpts(title="Taxa de escolarização"))
bar.set_series_opts(label_opts=opts.LabelOpts(is_show=False)) 
#bar.render("Evolução da pontuação média por região 2012-2017.html")
bar.render_notebook()

***MAPA MUNDI***

In [8]:
from pyecharts.charts import Map
from pyecharts import options as opts
import pandas as pd

tabela_educacao = pd.read_csv('tabela_wikipedia_educacao_eng.csv', sep = ",")


map = Map()
map.add('',tabela_educacao[['Country','Literate_rate']].values.tolist(),maptype='world')
map.set_series_opts(label_opts=opts.LabelOpts(is_show=False)) 
map.set_global_opts(
    visualmap_opts=opts.VisualMapOpts(min_=0,max_=100),
    legend_opts=opts.LegendOpts(is_show=False)
)

'''
country=list(tabela_educacao["País"])
percent=list(tabela_educacao["Alf_total"])
lista = [[country[i],percent[i]] for i in range(len(country))]
map.add("Alf_total", lista, maptype="world")
map.set_global_opts(
    visualmap_opts=opts.VisualMapOpts(max_=100,is_piecewise=False),
    legend_opts=opts.LegendOpts(is_show=False), 
 )
 '''

map.render_notebook() 
#map.render('mapa_mundi_educacao_version_eng.html')

***TABELA WIKI MAPA MUNDI ENG***

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

def obter_driver():
    return webdriver.Chrome()

def abrir_pagina(driver):
    for pag in range(1):
        driver.get('https://en.wikipedia.org/wiki/List_of_countries_by_literacy_rate')

In [3]:
driver = obter_driver()
abrir_pagina(driver)

In [4]:
import pandas as pd

country = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[1]/a')
literate_rate = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[2]')



rate = []
for i in range(len(country)):
    data = {'Country':country[i].text,
            'Literate_rate':literate_rate[i].text}

    rate.append(data)
    
df = pd.DataFrame(rate)
df

         Country                Literate_rate
0          World                        86.3%
1    Afghanistan                        38.2%
2        Albania                        97.6%
3        Algeria                        80.2%
4        Andorra  not reported by UNESCO 2015
..           ...                          ...
190    Venezuela                        95.4%
191      Vietnam                        94.5%
192        Yemen                        70.1%
193       Zambia                        63.4%
194     Zimbabwe                        86.5%

[195 rows x 2 columns]

In [24]:
df['Literate_rate'] = df['Literate_rate'].str.replace("%", "")
df['Literate_rate'] = df['Literate_rate'].str.replace(",", ".")
df['Literate_rate'] = df['Literate_rate'].str.replace("not reported by UNESCO 2015", "N/A")
df

         Country Literate_rate
0          World          86.3
1    Afghanistan          38.2
2        Albania          97.6
3        Algeria          80.2
4        Andorra           N/A
..           ...           ...
190    Venezuela          95.4
191      Vietnam          94.5
192        Yemen          70.1
193       Zambia          63.4
194     Zimbabwe          86.5

[195 rows x 2 columns]

In [25]:
#lista de paises que possuem dados, porem nao é possivel converter para numero

l1 = df.loc[df['Country'] == 'Bangladesh']
print(l1)
l2 = df.loc[df['Country'] == 'India']
print(l2)
l3 = df.loc[df['Country'] == 'Jordan']
print(l3)
l4 = df.loc[df['Country'] == 'Morocco']
print(l4)
l5 = df.loc[df['Country'] == 'Myanmar']
print(l5)
l6 = df.loc[df['Country'] == 'Pakistan']
print(l6)

       Country Literate_rate
14  Bangladesh  [note 3]73.9
   Country Literate_rate
76   India  [note 5]77.7
   Country   Literate_rate
85  Jordan  97.9 (in 2012)
     Country Literate_rate
118  Morocco       73.8[9]
     Country Literate_rate
120  Myanmar  75.6[note 7]
      Country       Literate_rate
131  Pakistan  59.1 (Year-\n2017)

In [26]:
tabela_excel = df.to_csv('tabela_wikipedia_educacao_eng.csv')
driver.quit()

In [27]:
import pandas as pd
tabela_educacao = pd.read_csv('tabela_wikipedia_educacao_eng.csv', sep = ",")
display(tabela_educacao)

     Unnamed: 0      Country Literate_rate
0             0        World          86.3
1             1  Afghanistan          38.2
2             2      Albania          97.6
3             3      Algeria          80.2
4             4      Andorra           NaN
..          ...          ...           ...
190         190    Venezuela          95.4
191         191      Vietnam          94.5
192         192        Yemen          70.1
193         193       Zambia          63.4
194         194     Zimbabwe          86.5

[195 rows x 3 columns]

***Tabela IBGE renda familiar***

In [60]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

def obter_driver():
    return webdriver.Chrome()

def abrir_pagina(driver):
    for pag in range(1):
        driver.get('https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/30129-ibge-divulga-o-rendimento-domiciliar-per-capita-2020')

In [61]:
driver = obter_driver()
abrir_pagina(driver)

In [62]:
import pandas as pd

unid_federacao = driver.find_elements_by_xpath('/html/body/main/div/div[1]/div[1]/div[3]/div/table/tbody/tr/td[1]')
rendimento = driver.find_elements_by_xpath('/html/body/main/div/div[1]/div[1]/div[3]/div/table/tbody/tr/td[2]')



per_capita = []
for l in range(len(rendimento)):
    data = {'Unidade da Federação':unid_federacao[l].text,
            'Rendimento per capita':rendimento[l].text}

    per_capita.append(data)
    
df = pd.DataFrame(per_capita)
df

   Unidade da Federação Rendimento per capita
0                Brasil                 1.380
1             Rondônia                  1.169
2                  Acre                   917
3              Amazonas                   852
4               Roraima                   983
5                 Pará                    883
6                 Amapá                   893
7             Tocantins                 1.060
8              Maranhão                   676
9                 Piauí                   859
10                Ceará                 1.028
11  Rio Grande do Norte                 1.077
12              Paraíba                   892
13           Pernambuco                   897
14              Alagoas                   796
15              Sergipe                 1.028
16                Bahia                   965
17         Minas Gerais                 1.314
18       Espírito Santo                 1.347
19       Rio de Janeiro                 1.723
20            São Paulo                 1.814
21               Paraná                 1.508
22       Santa Catarina                 1.632
23    Rio Grande do Sul                 1.759
24   Mato Grosso do Sul                 1.488
25          Mato Grosso                 1.401
26                Goiás                 1.258
27     Distrito Federal                 2.475

In [2]:
import pandas as pd
rend_pc = pd.read_csv('Rendimento_PC-2019.csv', sep = ";")
rend_2019pc= rend_pc[['Abertura geográfica', 'ind', 'classe', 'sub.classe', 'Unid', '2019']]
rend_2019pc

,Abertura geográfica,ind,classe,sub.classe,Unid,2019
0,Norte,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),872
1,Nordeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),884
2,Sudeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1720
3,Sul,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1701
4,Centro-Oeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1580

In [3]:
rend_2019pc = rend_2019pc.rename(columns={'2019': 'ANO2019'})
rend_2019pc

,Abertura geográfica,ind,classe,sub.classe,Unid,ANO2019
0,Norte,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),872
1,Nordeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),884
2,Sudeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1720
3,Sul,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1701
4,Centro-Oeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1580

In [4]:
rend_2019pc['ANO2019'] = rend_2019pc.ANO2019.astype(float)
rend_2019pc

,Abertura geográfica,ind,classe,sub.classe,Unid,ANO2019
0,Norte,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),872.0
1,Nordeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),884.0
2,Sudeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1720.0
3,Sul,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1701.0
4,Centro-Oeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1580.0

In [5]:
#Total de rendimentos per capita

total_rendpc = rend_2019pc['ANO2019'].sum()
total_rendpc

6757.0

In [10]:
#Rendimento per capita da região Norte do Brasil

norte_rendpc = rend_2019pc.iloc[0]['ANO2019']
norte_rendpc

872.0

In [15]:
#O quanto a região Norte representa do total de rendimentos per capita

porcentagem_n = round(((norte_rendpc*100)/total_rendpc), 2)
porcentagem_n

12.91

In [11]:
#Rendimento per capita da região Nordeste do Brasil

nordeste_rendpc = rend_2019pc.iloc[1]['ANO2019']
nordeste_rendpc

884.0

In [16]:
#O quanto a região Nordeste representa do total de rendimentos per capita

porcentagem_ne = round(((nordeste_rendpc*100)/total_rendpc), 2)
porcentagem_ne

13.08

In [19]:
#Rendimento per capita da região Sudeste do Brasil

sudeste_rendpc = rend_2019pc.iloc[2]['ANO2019']
sudeste_rendpc

1720.0

In [21]:
#O quanto a região Sudeste representa do total de rendimentos per capita

porcentagem_se = round(((sudeste_rendpc*100)/total_rendpc), 2)
porcentagem_se

25.46

In [20]:
#Rendimento per capita da região Sul do Brasil

sul_rendpc = rend_2019pc.iloc[3]['ANO2019']
sul_rendpc

1701.0

In [22]:
#O quanto a região Sul representa do total de rendimentos per capita

porcentagem_s = round(((sul_rendpc*100)/total_rendpc), 2)
porcentagem_s

25.17

In [17]:
#Total de Rendimento per capita das regiões Sul e Sudeste do Brasil

sul_sudeste_rendpc = rend_2019pc.iloc[3]['ANO2019'] + rend_2019pc.iloc[2]['ANO2019']
sul_sudeste_rendpc

3421.0

In [18]:
#O quanto as regiões Sul e Sudeste representam do total de rendimentos per capita

porcentagem_s_se = round(((sul_sudeste_rendpc*100)/total_rendpc), 2)
porcentagem_s_se

50.63

In [25]:
#Rendimento per capita da região Centro-Oeste do Brasil

centro_oeste_rendpc = rend_2019pc.iloc[4]['ANO2019']
centro_oeste_rendpc

1580.0

In [24]:
#O quanto a região Centro-Oeste representa do total de rendimentos per capita

porcentagem_co = round(((centro_oeste_rendpc*100)/total_rendpc), 2)
porcentagem_co

23.38

In [26]:
#Adicinando uma nova coluna com porcentagem de representação do total de cada região

representatividade = [porcentagem_n, porcentagem_ne, porcentagem_se, porcentagem_s, porcentagem_co]
rend_2019pc['Representação do total (%)'] = representatividade
rend_2019pc

,Abertura geográfica,ind,classe,sub.classe,Unid,ANO2019,Representação do total (%)
0,Norte,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),872.0,12.91
1,Nordeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),884.0,13.08
2,Sudeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1720.0,25.46
3,Sul,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1701.0,25.17
4,Centro-Oeste,Rendimento médio mensal real domiciliar per ca...,Classes simples de percentual das pessoas em o...,Total,(R$),1580.0,23.38